apiVersion: apps/v1
kind: Deployment
metadata:
  name: rightontime-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rightontime-frontend
  template:
    metadata:
      labels:
        app: rightontime-frontend
    spec:
      containers:
      - name: frontend
        image: rightontime-frontend:latest
        imagePullPolicy: IfNotPresent   # üî• ESTA L√çNEA
        ports:
        - containerPort: 80
